### PR TITLE
New classes: FfmpegProcessFactory, ArgumentsValidator, VideoInfoProvider

### PR DESCRIPTION
**Pull request by InB4DevOps**
Will later also use FfmpegProcessFactory for interval mode

### CODE REVIEW

**Comment by InB4DevOps** [comment]
Can you believe that I started with python just 10 days ago? :)

**Comment by InB4DevOps** [comment]
btw: 
when encoding, instead of `"-c:a", "copy", "-c:s", "copy", "-movflags", "+faststart"`
we're now using `"-an", "-sn"`

which omits audio and subtitles (which we do not need for video quality comparison) and we also don't need `"-movflags", "+faststart"` cause we're not streaming the output nor uploading to youtube.

**Comment by InB4DevOps** [comment]
btw2: the const "METRICS_EXPLANATION" is back but no extra module for it
constants increase the readability and should we need to change the string we just have to do it in a single place.

**Comment by CrypticSignal** [comment]
> btw: 
> 
> when encoding, instead of `"-c:a", "copy", "-c:s", "copy", "-movflags", "+faststart"`
> 
> we're now using `"-an", "-sn"`
> 
> 
> 
> which omits audio and subtitles (which we do not need for video quality comparison) and we also don't need `"-movflags", "+faststart"` cause we're not streaming the output nor uploading to youtube. 

I will check the pull request properly later but the user may want to watch/use the transcoded version(s) so it's better to keep the audio and subtitles. I don't really see a drawback in keeping them, those streams are copied rather than converted so removing them won't make any meaningful (if any) change to the time taken for this program to do its thing. 

This program doesn't just allow you to calculate quality metrics but it also keeps the transcoded files. Why will most people want to check different transcode settings? Because they actually want to transcode the video to save space or for compatibility reasons. If they like the result of one of the transcodes but the audio was removed, it was a waste of time in a sense since now the user has to manually transcode the video with the setting that they liked instead of being able to using the transcode provided by this program.

I'm not sure how much extra time movflags fastart adds but perhaps it could become an optional setting.

**Comment by InB4DevOps** [comment]
I think we might need to talk about the goal of VQM.

Is it rather
a) finding that CRF / preset sweetspot for an encode that you will do after VQM did its thing

or

b) transcoding & analyzing an entire movie / clip multiple times only to then throw away the results that didn't meet VMAF expectations? 

Personally I see VQM best for doing "a". I'd rather find that encoder setting that gets me my desired VMAF value (eg by using interval /overview mode and then CRF or preset comparison; this is usually pretty fast as it only encodes a small percentage of the actual video) than have VQM also do the transcoding of the entire video for me - cause transcoding & analyzing the same video over and over again is the real waste of time.  

Additionally FFmpeg has its own way of dealing with copying audio and subtitle streams; it does **not** copy _all_ audio & video streams but just takes the ones it deems necessary (iirc based on locale system settings) - try it yourself. 
(That might be a real annoyance for users of this program, to find that their beloved subtitles or audio streams are gone after VQM did its thing.) 

Take a movie with many audio and subtitle streams and make a quick transcode eg
`ffmepg -ss 00:10:00 - i <movie_with_audios_and_subtitles.ext> -t 10 -c:v libx264 -c:a copy -c:s copy <output.ext>`

and then compare `ffprobe -hide_banner original.mkv` with `ffprobe -hide_banner output.mkv` 

In my example this is the output from `ffprobe -hide_banner original.mkv`
```
ffprobe -hide_banner original.mkv
Input #0, matroska,webm, from 'original.mkv':
  Metadata:
    encoder         : libebml v0.7.7 + libmatroska v0.8.1
    creation_time   : 2009-01-05T18:37:03.000000Z
  Duration: 02:57:09.18, start: 0.000000, bitrate: 17045 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      title           : DTS 5.1, 1536 kbps
    Stream #0:2(fre): Subtitle: ass
    Metadata:
      title           : French
    Stream #0:3(ger): Subtitle: ass
    Metadata:
      title           : German
    Stream #0:4(gre): Subtitle: ass
    Metadata:
      title           : Greek
    Stream #0:5(pol): Subtitle: ass
    Metadata:
      title           : Polish
    Stream #0:6(por): Subtitle: ass
    Metadata:
      title           : Brazillian
    Stream #0:7(rum): Subtitle: ass
    Metadata:
      title           : Romanian
    Stream #0:8(slv): Subtitle: ass
    Metadata:
      title           : Slovenian
    Stream #0:9(spa): Subtitle: ass
    Metadata:
      title           : Spanish
    Stream #0:10(scc): Subtitle: ass
    Metadata:
      title           : Serbian
    Stream #0:11(bul): Subtitle: ass
    Metadata:
      title           : Bulgarian
    Stream #0:12(cze): Subtitle: ass
    Metadata:
      title           : Czech
    Stream #0:13(dut): Subtitle: ass
    Metadata:
      title           : Dutch
    Stream #0:14(eng): Subtitle: ass (default)
    Metadata:
      title           : English
    Stream #0:15(fin): Subtitle: ass
    Metadata:
      title           : Finnish
    Stream #0:16(eng): Audio: vorbis, 48000 Hz, stereo, fltp
    Metadata:
      title           : Director's Commentary, Vorbis 2.0
    Stream #0:17(ger): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      title           : Deutsch@Robby
    Stream #0:18(ger): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Metadata:
      title           : Deutsch@Robby@AC32.0.192kbit/s
    Stream #0:19: Attachment: ttf
    Metadata:
      filename        : CronosPro-Bold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:20: Attachment: ttf
    Metadata:
      filename        : CronosPro-Semibold.ttf
      mimetype        : application/x-truetype-font
    Stream #0:21: Attachment: ttf
    Metadata:
      filename        : CronosPro-SemiboldIt.ttf
      mimetype        : application/x-truetype-font
```

and this is the output of `ffprobe -hide_banner output.mkv`
```
ffprobe -hide_banner output.mkv
Input #0, matroska,webm, from 'output.mkv':
  Metadata:
    ENCODER         : Lavf58.45.100
  Duration: 00:00:15.33, start: 0.000000, bitrate: 6212 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      ENCODER         : Lavc58.91.100 libx264
      DURATION        : 00:00:12.314000000
    Stream #0:1(ger): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s (default)
    Metadata:
      title           : Deutsch@Robby
      DURATION        : 00:00:12.320000000
    Stream #0:2(fre): Subtitle: ass (default)
    Metadata:
      title           : French
      DURATION        : 00:00:15.334000000
```

See how it kept only one audio and one subtitle stream? I have looked into this before and there does not seem to be a way to tell ffmpeg to keep **all** audio & subtitle streams; one has to either let ffmpeg decide or use `-map` to select the streams manually. 

Regarding `faststart` please see: https://superuser.com/questions/856025/any-downsides-to-always-using-the-movflags-faststart-parameter

according to their tests it doesn't hurt to always use it but I don't see a benefit of having it at all. I won't mind if you choose to keep it in VQM, I just wanted to clarify that we don't actually need it (also this option is only for MP4, M4A, M4V, MOV output)

**Comment by CrypticSignal** [comment]
The main goal of this program is **a)**, but not everyone is going to be transcoding a movie. It could just be a particular scene, a music video, some drone footage, something someone recorded on their phone in 4K but they're running out of space on their phone, and so on. There are many types of videos that someone may have, and not all of them will be long. 

I just did some testing to see how much time keeping the audio stream adds. I used a video that is 1 hour and 52 minutes long, and I logged the time taken to run with `-an` and with `-c:a copy`, e.g.

`ffmpeg -i video.mp4 -c:v copy -an noaudio.mp4`
and
`ffmpeg -i video.mp4 -c:v copy -c:a copy audio.mp4`

With `an`, the time taken was 165.1 seconds.
With `-c:a copy`, the time taken was 216.9 seconds.

I don't have a powerful PC, it's an [Intel i7-3667](https://ark.intel.com/content/www/us/en/ark/products/64898/intel-core-i7-3667u-processor-4m-cache-up-to-3-20-ghz.html), but still, there's a 31% increase in completion time so perhaps there's a case to be made for removing the audio and subtitle streams. So I think, at least for now, let's go ahead with `-an` and `-sn`. Later we could add the option of allowing the user to choose whether they want the other streams to be kept. With something like `--keep-all-streams`.

> Additionally FFmpeg has its own way of dealing with copying audio and subtitle streams; it does not copy all audio & video streams but just takes the ones it deems necessary (iirc based on locale system settings) - try it yourself.

By default, FFmpeg keeps 1 stream of each type, based on the following criteria:

- [Video] it will keep the video stream with the highest resolution.
- [Audio] it will keep the audio stream that has the most channels.
- [Subtitles] it will keep the first subtitle stream found but there’s a caveat, the output format’s default subtitle encoder can be either text-based or image-based, and only a subtitle stream of the same type will be chosen.

In the case where several streams of the same type rate equally, the stream with the lowest index is chosen.
Data or attachment streams are not automatically selected and can only be included using -map.

[Here's ](https://ffmpeg.org/ffmpeg.html#Automatic-stream-selection )the source of the above information.
> I have looked into this before and there does not seem to be a way to tell ffmpeg to keep all audio & subtitle streams

You can tell FFmpeg to keep all streams with `-map 0`.

**Comment by BassThatHertz** [comment]
> Regarding faststart please see: https://superuser.com/questions/856025/any-downsides-to-always-using-the-movflags-faststart-parameter

> according to their tests it doesn't hurt to always use it but I don't see a benefit of having it at all. 

I just tested this with the same video that I referenced in the above comment. 359.4 seconds with `-an -movflags faststart`, 393.9 seconds with `-c:a copy -movflags faststart`. This is considerably more than 165.1 seconds and 216.9 seconds, respectively. So I agree with removing `-movflags +faststart` is a good idea. I didn't think it would add that much extra time.

**Comment by InB4DevOps** [comment]
I'm a Delphi software engineer. :)
If you want I can add comments to the new source? Or just ask and I will

**Comment by BassThatHertz** [comment]
Do you have Discord? If so, what's your username?

**Comment by InB4DevOps** [comment]
Yeah, I have discord. Will send my username tomorrow, won't be at my PC today any more.

**Comment by InB4DevOps** [comment]
paulbaeumer#0717

**Pull request merged**
